### ISSUE TITLE
Errors in logfile

### ISSUE THREAD

**Issue by Marcel-a** [ScreepsMods/screepsmod-mongo#17]
I'm getting following errors multiple times in a second and scritp-execution does not work:

logs/engine_runner1.log
>TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at env.get.then.compressed (/screeps_mongo/node_modules/@screeps/driver/lib/index.js:76:32)
    at _fulfilled (/screeps_mongo/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/screeps_mongo/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/screeps_mongo/node_modules/q/q.js:816:13)
    at /screeps_mongo/node_modules/q/q.js:624:44
    at runSingle (/screeps_mongo/node_modules/q/q.js:137:13)
    at flush (/screeps_mongo/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

logs/engine_processor2.log

>Error processing room W5N4: Error: Could not load terrain data
    at Object.search (/screeps_mongo/node_modules/@screeps/driver/lib/path-finder.js:134:23)
    at findPath (/screeps_mongo/node_modules/@screeps/engine/dist/processor/common/fake-runtime.js:182:33)
   at Object.moveTo (/screeps_mongo/node_modules/@screeps/engine/dist/processor/common/fake-runtime.js:228:22)
    at module.exports (/screeps_mongo/node_modules/@screeps/engine/dist/processor/intents/creeps/keepers/pretick.js:56:37)
    at _loop (/screeps_mongo/node_modules/@screeps/engine/dist/processor.js:195:78)
    at /screeps_mongo/node_modules/@screeps/engine/dist/processor.js:206:17
    at _fulfilled (/screeps_mongo/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/screeps_mongo/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/screeps_mongo/node_modules/q/q.js:816:13)
    at /screeps_mongo/node_modules/q/q.js:570:49

Mongo version: MongoDB shell version v4.0.6

**Comment by ags131** [comment]
Answered in slack, but posting here for anyone else that comes across it :)
`map.updateTerrainData()` will fix this, its an issue with the cached terrain data not importing correctly.
I'm leaving this open to remind me to look into fixing the import later

**Comment by mlinky** [comment]
Hi, sorry for the novice question - how can this be automated so I don't have to remember to put it into the CLI each time please?

**Comment by ags131** [comment]
This was fixed in 9ba6ec3d0ba69328706c55591a751be15dc0be7a, so just make sure  to update and you should be fine :)

**Comment by mlinky** [comment]
Thanks

**Comment by mlinky** [comment]
@ags131 Actually, I literally only installed today using npm, how can I check my current version please?

**Comment by ags131** [comment]
`npm list screepsmod-mongo` should show the version, latest is `2.4.7`. The fix is in the code for `system.resetAllData()`, so don't forget to run that after install :)

**Comment by mlinky** [comment]
@ags131 I've followed your instructions above. I can confirm I am on 2.4.7 and I have run system.resetAllData()
I've started a new private server and unless I run map.updateTerrainData() the server doesn't even manage to run the game loop.

**Comment by ags131** [comment]
I'll reopen this, I'll have to poke at it again, I thought I had fixed this :/

**Comment by mlinky** [comment]
Sorry :( 

Still seeing Error processing room W4N6: Error: Could not load terrain data even with the server sort of working.

**Comment by ags131** [comment]
Haven't seen this issue pop up at all recently, closing.
